"use client";
import { FiltersProvider } from "@/context/FiltersProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Layout } from "@/components/Layout";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Catalogo INET",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <FiltersProvider>
        <body className={inter.className}>
          <Layout>{children}</Layout>
        </body>
      </FiltersProvider>
    </html>
  );
}
